// <auto-generated />
using Homework_22.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homework_22.Migrations
{
    [DbContext(typeof(DiaryContext))]
    partial class DiaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Homework_22.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "548-9419 Ac St.",
                            Iban = "MC4687627477700586662925905",
                            Name = "Clinton",
                            Phone = "073-950-032",
                            Surname = "Nielsen"
                        },
                        new
                        {
                            Id = 2,
                            Address = "P.O. Box 755, 5715 Velit Street",
                            Iban = "DK0458275512361305",
                            Name = "Summer",
                            Phone = "981-871-867",
                            Surname = "Horton"
                        },
                        new
                        {
                            Id = 3,
                            Address = "5539 Elit. St.",
                            Iban = "IE50OCEY16214666156540",
                            Name = "Brock",
                            Phone = "644-470-655",
                            Surname = "Benson"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ap #972-9103 Eu Rd.",
                            Iban = "SM7625407558845802833383352",
                            Name = "Donovan",
                            Phone = "021-627-378",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            Id = 5,
                            Address = "432-4010 Molestie Road",
                            Iban = "AL04700264981286482617074842",
                            Name = "Martena",
                            Phone = "464-878-841",
                            Surname = "Stewart"
                        },
                        new
                        {
                            Id = 6,
                            Address = "P.O. Box 351, 8135 Lorem Av.",
                            Iban = "PL39719618279189562460931448",
                            Name = "Breanna",
                            Phone = "436-251-379",
                            Surname = "Benson"
                        },
                        new
                        {
                            Id = 7,
                            Address = "448-9849 Blandit Ave",
                            Iban = "GB98GWGL12119886433060",
                            Name = "Octavia",
                            Phone = "494-387-366",
                            Surname = "Cleveland"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
